// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCo4DXqLTsUiNEOu8ew9HBWmBOtsNWu7A',
    appId: '1:278776980111:web:b1f6e8b51cb284327346fa',
    messagingSenderId: '278776980111',
    projectId: 'final2-7bda5',
    authDomain: 'final2-7bda5.firebaseapp.com',
    storageBucket: 'final2-7bda5.firebasestorage.app',
    measurementId: 'G-PV6NC62ZFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWACnmcokz9L4GpzOfp0YjDAdFVAmJeb0',
    appId: '1:278776980111:android:922aaaffcecc2fd17346fa',
    messagingSenderId: '278776980111',
    projectId: 'final2-7bda5',
    storageBucket: 'final2-7bda5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaAAyw1IquORUaydz0r4TzTlcFdqpXRnM',
    appId: '1:278776980111:ios:634697c5fa3ef3327346fa',
    messagingSenderId: '278776980111',
    projectId: 'final2-7bda5',
    storageBucket: 'final2-7bda5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaAAyw1IquORUaydz0r4TzTlcFdqpXRnM',
    appId: '1:278776980111:ios:634697c5fa3ef3327346fa',
    messagingSenderId: '278776980111',
    projectId: 'final2-7bda5',
    storageBucket: 'final2-7bda5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCo4DXqLTsUiNEOu8ew9HBWmBOtsNWu7A',
    appId: '1:278776980111:web:808346f1ca7a329c7346fa',
    messagingSenderId: '278776980111',
    projectId: 'final2-7bda5',
    authDomain: 'final2-7bda5.firebaseapp.com',
    storageBucket: 'final2-7bda5.firebasestorage.app',
    measurementId: 'G-E34N6WH0V1',
  );
}
